# Generated by Django 4.1.2 on 2022-10-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contributor", old_name="contributor", new_name="user",
        ),
    ]
